### ISSUE TITLE
Make plugin raise error if xvfb ain't installed

### ISSUE THREAD

**Issue by ionelmc** [The-Compiler/pytest-xvfb#12]
This would make some people (which should not be named but easy to guess who am I) feel less stupid when they forget to install xvfb. 😬

**Comment by The-Compiler** [comment]
It already prints a warning - that not being an error is a feature, so your tests still run without Xvfb.

**Comment by ionelmc** [comment]
Maybe an `--xvfb` option to make it error out?

**Comment by The-Compiler** [comment]
Sorry for the delay! I don't really see the use case for that still - if you read enough of the documentation to find out about `--xvfb`, you should probably also find out about installing Xvfb, no? Or would this be something you'd add to the `pytest.ini` for your project?

FWIW I'm fine with a PR for it, though :wink:
