### ISSUE TITLE
Warn if xvfb not available

### ISSUE THREAD

**Issue by ionelmc** [The-Compiler/pytest-xvfb#2]
There should be a warning, so yuu can easily tell if you're missing some system packages.

**Comment by The-Compiler** [comment]
I'm not sure about this to be honest - I'd rather have it work transparently, and you'll surely notice if windows are popping up and all :wink:

The only scenario where it could be useful is for people contributing to some project, annoyed by those windows, and not reading the contribution guidelines, IMHO?

**Comment by ionelmc** [comment]
Or maybe just raise an error? Something is wrong if you don't have xvfb installed and you try to use the fixuture.

On the other hand, would you ever run tests with this fixture on windows?

**Comment by The-Compiler** [comment]
I think you're missing the point :wink: The fixture is mainly there to give you the display number if you ever need it, but other than that it's not very important.

The point of the plugin is to run Xvfb (without you doing anything other than installing the plugin), and to not do so if it's not available (i.e. fall back on normal X). When e.g. using `tox`, it'd be installed on Windows/OS X too, and just not do anything.

I think the important bit is that nothing stops working if Xvfb isn't available - it just is a little bit less pleasant.

**Comment by ionelmc** [comment]
I see, you're right. So you think a "pytest warning" is not worth having? It would be a single one ...

**Comment by The-Compiler** [comment]
Maybe it is, yeah. I guess I can pass `--no-xvfb` on my buildbot (which has a real X server), and only display the warning on Linux.

**Comment by ionelmc** [comment]
So you're ok with a warning if the xvfb bin ain't available?

**Comment by The-Compiler** [comment]
Was that an offer for a PR? :smile:

I am - but I think only under those circumstances:

- Only on Linux (nothing you can do on Windows anyways, no idea about OS X)
- Only when `--no-xvfb` is not given
- Only when `DISPLAY` is actually available in the environment (if it isn't, either the tests will fail anyway, or they'll be skipped like in qutebrowser)

I'm not so sure about 3), but I think it makes sense. What do you think?

**Comment by ionelmc** [comment]
About (3) - the tests would fail anyway due to no DISPLAY, I don't think anyone is gonna see the tiny warning in the sea of failures :D

**Comment by mandeep** [comment]
I agree that a warning should be displayed if xvfb is not available. I'd be happy to submit a pull request; however, I'm not really sure where one could fit the warning statement.

From first glance, it looks like you could add with capsys.disabled() somewhere in https://github.com/The-Compiler/pytest-xvfb/blob/master/pytest_xvfb.py#L134, but I don't think that capsys can be passed as an argument to that function.

Thoughts?

**Comment by The-Compiler** [comment]
I guess you could just add a pytest warning from there - I know there are some plugins using pytest warnings, but I can't find one right now :wink:

**Comment by ionelmc** [comment]
Come on, the benchmark plugin has dozens of warnings :P

**Comment by The-Compiler** [comment]
Dang, I knew one of your plugins must use it, but I only checked pytest-cov :laughing:

**Comment by mandeep** [comment]
Hi @The-Compiler! I recently ran tests while pytest-xfvb installed and without Xvfb installed. Due to the way the warning is handled, I had to scroll to the top of the entire test results to see the warning. Even then, it was hard to see. What do you think about using pytest warnings instead? Were you able to see the warning fine when running tests on a large test suite?

**Comment by The-Compiler** [comment]
Anything affecting the exit status is not accceptable, IMHO.

**Comment by mandeep** [comment]
Yeah, I guess it's a lesser of the evils type of thing. I'll let you know if I come up with something.
