### ISSUE TITLE
travis build freezes 

### ISSUE THREAD

**Issue by mluerig** [The-Compiler/pytest-xvfb#21]
I am developing a program that requires some user interaction with a gui. For testing and CI I have monkey patched some user input, but showing the results of that input is still essential to the testing and code coverage, so windows need to pop up. In windows environments (appveyor) the tests run without any issues, but on Travis where I test in a linux environment the test didn't finish and I got "cannot connect to X server". After stumbling upon your package and installing, something happens, but then the console freezes. The console is printing the content of a yaml-configuration file that is opened (and used internally), but it shouldn't be printed like that. 

Sorry for being rather vague, but do you have any idea what's going on here?

https://travis-ci.org/github/mluerig/phenopype/builds/682899151

**Comment by mluerig** [comment]
I collected some more information: when I run tox on my local machine (Ubuntu 18.04) I get `: cannot connect to X server` . When I then install xvfb with `sudo apt-get install xvfb` I get `WARNING: terminal is not fully functional` and that config file is opened with vim. I quit, and the rest of the tests run normally, except one that involves mobing a window (throws the following error: `cv2.error: OpenCV(3.4.9) /io/opencv/modules/highgui/src/window_QT.cpp:580: error: (-27:Null pointer) NULL guiReceiver (please create a window) in function 'cvMoveWindow'` - that makes sense, if no window is opened).

**Comment by The-Compiler** [comment]
Sorry for the late answer, this got lost in my inbox for a while. No idea what's going on here I'm afraid, and I'm pretty sure you'll see the same issues without pytest-xvfb as well.

If you run `tox` locally and want it to use your real GUI environment (without `pytest-xvfb`), you will need to set something like `passenv = DISPLAY` for the respective testenv in `tox.ini`. Let me know if you need more help after that, and I'll help if I can - but I'm closing this, as I'm pretty confident it's not pytest-xvfb causing trouble here.
