### ISSUE TITLE
xvfb snapshots?

### ISSUE THREAD

**Issue by up2l8** [The-Compiler/pytest-xvfb#25]
Is it possible to create .png snapshots of the frame buffer before/during/after tests are run?  Or maybe on a periodic basis? It could be useful in debugging and such.

**Comment by The-Compiler** [comment]
I like the idea, but I wonder if this wouldn't fit better into a separate pytest plugin - is there something in that functionality that would be specific to Xvfb?

**Comment by up2l8** [comment]
I think you are right.  I was thinking you'd interact with the frame buffer file directly but it makes much more sense to use available screen capture tools with DISPLAY set correctly.

**Comment by The-Compiler** [comment]
Closing this then - I'd probably use that functionality myself for [qutebrowser](https://www.qutebrowser.org/), but I don't think it should be part of the Xvfb plugin. Maybe some day I'll find the time for a pytest-screenshots plugin, unless someone else wants to write one :wink:
