### ISSUE TITLE
Unused links in README

### ISSUE THREAD

**Issue by hyandell** [The-Compiler/pytest-xvfb#27]
Noting that the README has links to three licenses without those links being used:

.. _`BSD-3`: http://opensource.org/licenses/BSD-3-Clause
.. _`GNU GPL v3.0`: http://www.gnu.org/licenses/gpl-3.0.txt
.. _`Apache Software License 2.0`: http://www.apache.org/licenses/LICENSE-2.0

**Comment by The-Compiler** [comment]
Well spotted! Also reported here: https://github.com/pytest-dev/cookiecutter-pytest-plugin/issues/57
