### ISSUE TITLE
Logging that the plugin is installed and enabled during a pytest run?

### ISSUE THREAD

**Issue by matanster** [The-Compiler/pytest-xvfb#28]
Thanks a lot for this plugin! 

I was just wondering whether it would be a good idea to somehow have pytest or the plugin itself output that this plugin is enabled, when running pytest. 

Maybe that's already an option in pytest which I didn't find. It would just help when a nascent person will be wondering why GUI doesn't open up during the tests. admittedly I couldn't find the option to list active plugins during a pytest run. This may serve the same aspect of being informative as the already included warning in the case that the plugin is installed but xvfb itself is not.

Reasons not to add this can be backward compatibility as well avoiding to intrude the test output log. Or maybe it's already possible with some pytest option, or people think that having a pytest plugin installed should be the lead to figuring out that it is enabled for a project. It's admittedly my first pytest plugin that I'm using (and it simply works!).

**Comment by The-Compiler** [comment]
pytest already does this out of the box:

```
============================= test session starts ==============================
platform linux -- Python 3.8.13, pytest-7.1.1, pluggy-1.0.0
rootdir: /home/florian/proj/pytest-xvfb, configfile: pytest.ini
plugins: xvfb-2.0.0
collected 115 items 
```

so I don't think there's anything to do here. Glad to hear you're happy with the plugin though!
