### ISSUE TITLE
`dri3 extension not supported` in GitHub Actions run

### ISSUE THREAD

**Issue by palewire** [The-Compiler/pytest-xvfb#29]
I'm attempting to use your excellent library to run tests of a Playwright application. Everything works perfect when I run the tests on my laptop, but jobs on GitHub Actions are failing with an error that says:

```
<launch...ffer_support_x11.cc(44)] dri3 extension not supported
```

I suspect this must be something with how the display server and other bits are installed on the cloud image. I just don't really get it. I've been mucking with the $DISPLAY setting and other bits but have yet to crack it.

Here's a recent run that failed:
https://github.com/palewire/news-homepages/runs/6247992407?check_suite_focus=true

Any help would be much appreciated.

**Comment by The-Compiler** [comment]
This seems to be an issue around Xvfb and Playwright in general, not specific to this plugin: https://github.com/microsoft/playwright-python/issues/1277

**Comment by The-Compiler** [comment]
This seems to be an issue around Xvfb and Playwright in general, not specific to this plugin: https://github.com/microsoft/playwright-python/issues/1277
