### ISSUE TITLE
Shouldn't the fixture be session scoped?

### ISSUE THREAD

**Issue by ionelmc** [The-Compiler/pytest-xvfb#3]
I was thinking that maybe this should be session scoped (I'd like to use it in another session scoped fixture)

Plus there's not much value in having a clean xvfb process for each tests right?

The only downside is that the xvfb process might be around for longer than necessary. 

What do you think?

**Comment by ionelmc** [comment]
Ah, now I read the code, the svfb process is practically session scoped. I don't make sense to have the fixture function scoped imo.

**Comment by The-Compiler** [comment]
I agree, it would make more sense for it to be session-scoped.
