### ISSUE TITLE
Aborted error while running tests on GitHub Actions

### ISSUE THREAD

**Issue by gridhead** [The-Compiler/pytest-xvfb#41]
Here's the link to the logs

https://github.com/gridhead/gi-loadouts/actions/runs/10934810089/job/30355521093?pr=154#step:6:494

The tests however run just fine locally 🤔

**Comment by The-Compiler** [comment]
This is unrelated to Xvfb, you're likely just missing dependencies for Qt to run. If you run pytest with `-s`, you'll find out what's happening exactly.

The [pytest-qt docs](https://pytest-qt.readthedocs.io/en/latest/troubleshooting.html#github-actions-azure-pipelines-travis-ci-and-gitlab-ci-cd) have a list, you might also want to fix the dev instructions in your README accordingly.

**Comment by gridhead** [comment]
I seem to have figured that out after the fact. Thanks for pointing me in the right direction.

Ref. https://github.com/gridhead/gi-loadouts/blob/test/.github/workflows/test.yml#L16-L29
